/* Generated By:JavaCC: Do not edit this line. BelaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BelaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int FUN = 6;
  /** RegularExpression Id. */
  int APAR = 7;
  /** RegularExpression Id. */
  int FPAR = 8;
  /** RegularExpression Id. */
  int ACHAVES = 9;
  /** RegularExpression Id. */
  int FCHAVES = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int SEQ = 12;
  /** RegularExpression Id. */
  int VIRGULA = 13;
  /** RegularExpression Id. */
  int ATRIB = 14;
  /** RegularExpression Id. */
  int FLOAT = 15;
  /** RegularExpression Id. */
  int BOOL = 16;
  /** RegularExpression Id. */
  int VOID = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int THEN = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int READINPUT = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int PRINTLN = 23;
  /** RegularExpression Id. */
  int SOMA = 24;
  /** RegularExpression Id. */
  int SUB = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int MENORQ = 30;
  /** RegularExpression Id. */
  int MAIORQ = 31;
  /** RegularExpression Id. */
  int COMPARA = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int TOKEN_id = 35;
  /** RegularExpression Id. */
  int TOKEN_numliteral = 36;
  /** RegularExpression Id. */
  int LETRA = 37;
  /** RegularExpression Id. */
  int DIGITO = 38;
  /** RegularExpression Id. */
  int DIGITOS = 39;
  /** RegularExpression Id. */
  int FACAO_OPCIONAL = 40;
  /** RegularExpression Id. */
  int EXPOENTE_OPCIONAL = 41;
  /** RegularExpression Id. */
  int LETRAOUDIGITO = 42;
  /** RegularExpression Id. */
  int FINAL_SUBLINHADO = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"fun\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"var\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"float\"",
    "\"bool\"",
    "\"void\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"readInput\"",
    "\"return\"",
    "\"printLn\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"true\"",
    "\"false\"",
    "<TOKEN_id>",
    "<TOKEN_numliteral>",
    "<LETRA>",
    "<DIGITO>",
    "<DIGITOS>",
    "<FACAO_OPCIONAL>",
    "<EXPOENTE_OPCIONAL>",
    "<LETRAOUDIGITO>",
    "<FINAL_SUBLINHADO>",
  };

}
